@startuml ldm-MuaHang
!pragma layout smetana
left to right direction

'------------------------------------------------------------------------------
' Chứng từ mua hàng
'------------------------------------------------------------------------------
entity ChungTuMuaHang
{
    *Id: uuid <<PK>> - ID bản ghi

    ' Thuộc tính nghiệp vụ chung
    LoaiNghiepVu: enum! - Loại nghiệp vụ (Mua hàng nhập kho, Mua hàng không qua kho)
    HinhThuc: enum! - Hình thức (Trong nước, Nhập khẩu)
    NhieuHoaDon: boolean - Có nhiều hóa đơn (true/false)

    ' Thông tin chứng từ null nếu có phiếu nhập kho
    SoChungTu: string - Số chứng từ
    NgayChungTu: date - Ngày chứng từ
    NgayHachToan: date - Ngày hạch toán
    MoTa: string - Diễn giải

    ' Thông tin loại tiền và tỷ giá
    LoaiTienId: uuid! <<FK>> - ID loại tiền tệ (reference đến ENT_LoaiTien)
    TyGia: numeric! - Tỷ giá

    ' Thông tin chiết khấu
    LoaiChietKhau: enum! - Loại chiết khấu (Theo tiền, Theo phần trăm, Không chiết khấu)
    GiaTriChietKhau: numeric - Giá trị chiết khấu (áp dụng nếu có chiết khấu) có thể là phần trăm hoặc tiền tùy theo loại chiết khấu

    ' Thông tin nhà cung cấp null nếu có phiếu nhập kho
    NhaCungCapId: uuid! <<FK>> - ID nhà cung cấp
    TenNhaCungCap: string! - Tên nhà cung cấp
    DiaChi: string - Địa chỉ nhà cung cấp

    ' Thông tin điều khoản thanh toán và nợ null nếu thanh toán ngay
    DieuKhoanThanhToanId: uuid <<FK>> - ID điều khoản thanh toán (reference đến ENT_DieuKhoanThanhToan)
    SoNgayDuocNo: int - Số ngày được nợ
    HanThanhToan: date - Hạn thanh toán

    ' Thông tin mua hàng
    NhanVienMuaHangId: uuid <<FK>> - ID nhân viên mua hàng

    ' Thông tin thanh toán
    ThanhToanNgay: boolean - Thanh toán ngay (true/false)
    HinhThucThanhToan: enum! - Hình thức thanh toán (Tiền mặt, Ủy nhiệm chi, Séc tiền mặt, Séc chuyển khoản)

    ' Nhóm thông tin tổng hợp theo chứng từ
    TongTienHangHoa: numeric - Tổng tiền hàng hóa trước khi chiết khấu
    TongTienChietKhau: numeric - Tổng tiền chiết khấu
    TongTienTruocThue: numeric - Tổng tiền trước thuế
    TongTienThueGTGT: numeric - Tổng tiền thuế GTGT
    TongTienSauThue: numeric - Tổng tiền sau thuế
    ChiPhi: numeric - Chi phí mua hàng
    TongTienThanhToan: numeric - Tổng tiền thanh toán

    ' Nhóm thông tin quy đổi
    TongTienHangHoaQuyDoi: numeric - Tổng tiền hàng hóa trước khi chiết khấu
    TongTienChietKhauQuyDoi: numeric - Tổng tiền chiết khấu
    TongTienTruocThueQuyDoi: numeric - Tổng tiền trước thuế
    TongTienThueGTGTQuyDoi: numeric - Tổng tiền thuế GTGT
    TongTienSauThueQuyDoi: numeric - Tổng tiền sau thuế
    ChiPhiQuyDoi: numeric - Chi phí mua hàng
    TongTienThanhToanQuyDoi: numeric - Tổng tiền thanh toán

    ' Nhóm thông tin thanh toán
    SoTienDaThanhToan: numeric - Số tiền đã thanh toán
    SoTienDaThanhToanQuyDoi: numeric - Số tiền đã thanh toán quy đổi

    ' Nhóm thông tin trạng thái
    TrangThaiChungTu: enum! - Trạng thái chứng từ (Chưa ghi sổ, Đã ghi sổ)
    TrangThaiHoaDon: enum! - Trạng thái hóa đơn (Đã có hóa đơn / Chưa có hóa đơn / Không có hóa đơn)
    TrangThaiNhanHoaDon: enum! - Trạng thái nhận hóa đơn (Đã có hóa đơn / Chưa có hóa đơn / Không có hóa đơn)
    TrangThaiThanhToan: enum! - Trạng thái thanh toán (Đã thanh toán / Chưa thanh toán / Đã thanh toán một phần)

    ' Thông tin giảm trừ do trả lại hoặc điều chỉnh giá
    TongTienGiamTru: numeric - Tổng tiền giảm trừ
    TongTienGiamTruQuyDoi: numeric - Tổng tiền giảm trừ quy đổi
}

entity ChungTuMuaDichVu {
    *Id: uuid <<PK>> - ID bản ghi
    LaChiPhiMuaHang: boolean! - Là chi phí mua hàng (true/false)
    NhieuHoaDon: boolean! - Có nhiều hóa đơn (true/false)

    ' Thông tin chứng từ null nếu có phiếu nhập kho
    SoChungTu: string! - Số chứng từ
    NgayChungTu: date! - Ngày chứng từ
    NgayHachToan: date! - Ngày hạch toán
    MoTa: string - Diễn giải

   ' Thông tin loại tiền và tỷ giá
    LoaiTienId: uuid <<FK>> - ID loại tiền tệ (reference đến ENT_LoaiTien)
    TyGia: numeric - Tỷ giá

    ' Thông tin chiết khấu
    LoaiChietKhau: enum! - Loại chiết khấu (Theo tiền, Theo phần trăm, Không chiết khấu)
    GiaTriChietKhau: numeric - Giá trị chiết khấu (áp dụng nếu có chiết khấu) có thể là phần trăm hoặc tiền tùy theo loại chiết khấu

    ' Thông tin nhà cung cấp null nếu có phiếu nhập kho
    NhaCungCapId: uuid! <<FK>> - ID nhà cung cấp
    TenNhaCungCap: string! - Tên nhà cung cấp
    DiaChi: string - Địa chỉ nhà cung cấp

    ' Thông tin điều khoản thanh toán và nợ null nếu thanh toán ngay
    DieuKhoanThanhToanId: uuid <<FK>> - ID điều khoản thanh toán (reference đến ENT_DieuKhoanThanhToan)
    SoNgayDuocNo: int - Số ngày được nợ
    HanThanhToan: date - Hạn thanh toán

    ' Thông tin mua hàng
    NhanVienMuaHangId: uuid <<FK>> - ID nhân viên mua hàng

    ' Thông tin thanh toán
    ThanhToanNgay: boolean - Thanh toán ngay (true/false)
    HinhThucThanhToan: enum! - Hình thức thanh toán (Tiền mặt, Ủy nhiệm chi, Séc tiền mặt, Séc chuyển khoản)

    ' Nhóm thông tin tổng hợp theo chứng từ
    TongTienHangHoa: numeric - Tổng tiền hàng hóa trước khi chiết khấu
    TongTienChietKhau: numeric - Tổng tiền chiết khấu
    TongTienTruocThue: numeric - Tổng tiền trước thuế
    TongTienThueGTGT: numeric - Tổng tiền thuế GTGT
    TongTienSauThue: numeric - Tổng tiền sau thuế
    TongTienThanhToan: numeric - Tổng tiền thanh toán

    ' Nhóm thông tin quy đổi
    TongTienHangHoaQuyDoi: numeric - Tổng tiền hàng hóa trước khi chiết khấu
    TongTienChietKhauQuyDoi: numeric - Tổng tiền chiết khấu
    TongTienTruocThueQuyDoi: numeric - Tổng tiền trước thuế
    TongTienThueGTGTQuyDoi: numeric - Tổng tiền thuế GTGT
    TongTienSauThueQuyDoi: numeric - Tổng tiền sau thuế
    TongTienThanhToanQuyDoi: numeric - Tổng tiền thanh toán

    ' Nhóm thông tin thanh toán
    SoTienDaThanhToan: numeric - Số tiền đã thanh toán
    SoTienDaThanhToanQuyDoi: numeric - Số tiền đã thanh toán quy đổi

    ' Nhóm thông tin trạng thái
    TrangThaiChungTu: enum - Trạng thái chứng từ (Chưa ghi sổ, Đã ghi sổ)
    TrangThaiHoaDon: enum! - Trạng thái hóa đơn (Đã có hóa đơn / Chưa có hóa đơn / Không có hóa đơn)
    TrangThaiNhanHoaDon: enum! - Trạng thái nhận hóa đơn (Đã có hóa đơn / Chưa có hóa đơn / Không có hóa đơn)
    TrangThaiThanhToan: enum - Trạng thái thanh toán (Đã thanh toán / Chưa thanh toán / Đã thanh toán một phần)

    ' Thông tin giảm trừ do trả lại hoặc điều chỉnh giá
    TongTienGiamTru: numeric - Tổng tiền giảm trừ
    TongTienGiamTruQuyDoi: numeric - Tổng tiền giảm trừ quy đổi
}

entity PhanBoChiPhiMuaHang {
    *Id: uuid <<PK>> - ID bản ghi
    ChungTuMuaHangId: uuid <<FK>> - ID chứng từ mua hàng (reference đến ENT_ChungTuMuaHang)
    ChungTuMuaDichVuId: uuid <<FK>> - ID chứng từ mua dịch vụ (reference đến ENT_ChungTuMuaDichVu)
    MaHangId: uuid <<FK>> - ID mã hàng được phân bổ (reference đến ENT_VatTu)
    ChiPhiPhanBo: numeric - Chi phí phân bổ vào hàng hóa
    ChiPhiPhanBoQuyDoi: numeric - Chi phí phân bổ quy đổi
}

entity HoaDonMua
{           
    *Id: uuid <<PK>> - ID bản ghi

    ' Phân loại hóa đơn
    LaHDVeSau: boolean - True: Hóa đơn về sau (Độc lập), False: Hóa đơn lập kèm chứng từ (Tích hợp)

    ' Thông tin hóa đơn
    SoHoaDon: string! - Số hóa đơn
    MauSoHoaDonId: uuid <<FK>> - ID mẫu số hóa đơn (reference đến ENT_MauSoHoaDon)
    KyHieuHoaDon: string - Ký hiệu hóa đơn
    NgayHoaDon: date! - Ngày hóa đơn
    NgayHachToan: date! - Ngày hạch toán
    MoTa: string - Ghi chú hóa đơn

    ' Thông tin loại tiền và tỷ giá
    LoaiTienId: uuid! <<FK>> - ID loại tiền tệ (reference đến ENT_LoaiTien)
    TyGia: numeric! - Tỷ giá

    ' Thông tin nhà cung cấp
    NhaCungCapId: uuid! <<FK>> - ID nhà cung cấp
    TenNhaCungCap: string! - Tên nhà cung cấp
    MaSoThue: string - Mã số thuế nhà cung cấp
    DiaChi: string - Địa chỉ nhà cung cấp

    ' Thông tin điều khoản thanh toán và nợ
    DieuKhoanThanhToanId: uuid <<FK>> - ID điều khoản thanh toán (reference đến ENT_DieuKhoanThanhToan)
    SoNgayDuocNo: int - Số ngày được nợ
    HanThanhToan: date - Hạn thanh toán

    ' Nhóm thông tin tổng hợp
    TongTienHangHoa: numeric - Tổng tiền hàng hóa trước khi chiết khấu
    TongTienChietKhau: numeric - Tổng tiền chiết khấu
    TongTienTruocThue: numeric - Tổng tiền trước thuế
    TongTienThueGTGT: numeric - Tổng tiền thuế GTGT
    TongTienSauThue: numeric - Tổng tiền sau thuế
    ChiPhi: numeric - Chi      phí mua hàng
    TongTienThanhToan: numeric - Tổng tiền thanh toán

    ' Nhóm thông tin quy đổi
    TongTienHangHoaQuyDoi: numeric - Tổng tiền hàng hóa trước khi chiết khấu
    TongTienChietKhauQuyDoi: numeric - Tổng tiền chiết khấu
    TongTienTruocThueQuyDoi: numeric - Tổng tiền trước thuế
    TongTienThueGTGTQuyDoi: numeric - Tổng tiền thuế GTGT
    TongTienSauThueQuyDoi: numeric - Tổng tiền sau thuế
    ChiPhiQuyDoi: numeric - Chi phí mua hàng
    TongTienThanhToanQuyDoi: numeric - Tổng tiền thanh toán

    ' Nhóm thông tin thanh toán
    TrangThaiThanhToan: enum - Trạng thái thanh toán (Đã thanh toán / Chưa thanh toán / Đã thanh toán một phần)
    SoTienDaThanhToan: numeric - Số tiền đã thanh toán
    SoTienDaThanhToanQuyDoi: numeric - Số tiền đã thanh toán

    ' Thông tin giảm trừ do trả lại hoặc điều chỉnh giá
    TongTienGiamTru: numeric - Tổng tiền giảm trừ
    TongTienGiamTruQuyDoi: numeric - Tổng tiền giảm trừ quy đổi
    
    ' Nhóm thông tin trạng thái
    TrangThaiChungTu: enum! - Trạng thái chứng từ (Chưa ghi sổ, Đã ghi sổ)
}

entity ChiTietHoaDon
{
    *Id: uuid <<PK>> - ID bản ghi
    HoaDonMuaId: uuid! <<FK>> - ID hóa đơn mua (reference đến ENT_HoaDonMua)

    ' Tham chiếu đến chứng từ gốc
    ChungTuId: uuid! <<FK>> - ID chứng từ mua hàng hoặc chứng từ mua dịch vụ (reference đến ENT_ChungTuMuaHang hoặc ENT_ChungTuMuaDichVu)

    ' Thông tin chi tiết hàng hóa/dịch vụ
    MaHangId: uuid <<FK>> - ID hàng hóa/dịch vụ (reference đến ENT_VatTu)
    TenHang: string - Tên hàng hóa/dịch vụ
    ThanhTienTruocThue: numeric - Thành tiền trước thuế
    ThanhTienTruocThueQuyDoi: numeric - Thành tiền trước thuế quy đổi

    ' Thông tin chi tiết thuế GTGT
    ThueSuatGTGTId: uuid <<FK>> - ID thuế suất GTGT (reference đến ENT_ThueSuatGTGT)
    TaiKhoanThueGTGTId: uuid <<FK>> - ID tài khoản thuế GTGT (reference đến ENT_HeThongTaiKhoan)
    TienThueGTGT: numeric - Tiền thuế GTGT
    TienThueGTGTQuyDoi: numeric - Tiền thuế GTGT quy đổi
    TinhChatThueGTGTId: uuid <<FK>> - ID tính chất thuế GTGT (reference đến ENT_TinhChatThueGTGT)

    ' Thông tin chi tiết tài khoản kế toán
    TaiKhoanCo: uuid! <<FK>> - ID tài khoản có (reference đến ENT_HeThongTaiKhoan)

    ' Thông tin tổng hợp
    TongTienTruocThue: numeric - Tổng tiền trước thuế
    TongTienThueGTGT: numeric - Tổng tiền thuế GTGT
    ThanhTienSauThue: numeric - Thành tiền sau thuế

    TongTienTruocThueQuyDoi: numeric - Tổng tiền trước thuế
    TongTienThueGTGTQuyDoi: numeric - Tổng tiền thuế GTGT quy đổi
    ThanhTienSauThueQuyDoi: numeric - Thành tiền sau thuế quy đổi
}

entity ChiTietChungTuMuaHang
{
    *Id: uuid! <<PK>> - ID bản ghi
    ' Tham chiếu tới các chứng từ liên quan
    ChungTuMuaHangId: uuid! <<FK>> - ID chứng từ mua hàng (reference đến ENT_ChungTuMuaHang)
    PhieuNhapKhoId: uuid <<FK>> - ID phiếu nhập kho (reference đến ENT_PhieuNhapKho)
    HoaDonMuaId: uuid <<FK>> - ID hóa đơn mua (reference đến ENT_HoaDonMua)

    ' Thông tin chi tiết hàng hóa
    MaHangId: uuid! <<FK>> - ID mã hàng (reference đến ENT_VatTu)
    TenHang: string - Tên hàng hóa
    SoLuong: numeric! - Số lượng
    DonGia: numeric! - Đơn giá
    DonGiaQuyDoi: numeric! - Đơn giá quy đổi
    ThanhTien: numeric! - Thành tiền
    ThanhTienQuyDoi: numeric! - Thành tiền
    ChietKhau: numeric - Chiết khấu
    ChietKhauQuyDoi: numeric - Chiết khấu
    ChietKhauPhanTram: numeric - Chiết khấu (%)
    DonViTinhId: uuid <<FK>> - ID đơn vị tính (reference đến ENT_DonViTinh)
    MaKhoId: uuid <<FK>> - ID kho (reference đến ENT_Kho)
    SoLo: string - Số lô
    HanSuDung: date - Hạn sử dụng

    ' Thông tin chi tiết tài khoản kế toán
    TaiKhoanNo: uuid! <<FK>> - ID tài khoản nợ (reference đến ENT_HeThongTaiKhoan)
    TaiKhoanCo: uuid! <<FK>> - ID tài khoản có (reference đến ENT_HeThongTaiKhoan)

    ' Thông tin chi tiết thuế GTGT
    ThueSuatGTGTId: uuid <<FK>> - ID thuế suất GTGT (reference đến ENT_ThueSuatGTGT)
    TaiKhoanThueGTGTId: uuid <<FK>> - ID tài khoản thuế GTGT (reference đến ENT_HeThongTaiKhoan)
    TienThueGTGT: numeric - Tiền thuế GTGT
    TienThueGTGTQuyDoi: numeric - Tiền thuế GTGT quy đổi
    TinhChatThueGTGTId: uuid <<FK>> - ID tính chất thuế GTGT (reference đến ENT_TinhChatThueGTGT)

    ' Thông tin chi tiết thuế nhập khẩu (nếu có)
    TaiKhoanThueNKId: uuid <<FK>> - ID tài khoản thuế NK (reference đến ENT_HeThongTaiKhoan)
    TienThueNK: numeric - Tiền thuế NK
    TienThueNKQuyDoi: numeric - Tiền thuế NK quy đổi
    PhanTramThueNK: numeric - Phần trăm thuế nhập khẩu (%)

    ' Thông tin chi tiết thuế tiêu thụ đặc biệt (nếu có)
    TaiKhoanThueTTDBId: uuid <<FK>> - ID tài khoản thuế TTDB (reference đến ENT_HeThongTaiKhoan)
    TienThueTTDB: numeric - Tiền thuế TTDB
    TienThueTTDBQuyDoi: numeric - Tiền thuế TTDB quy đổi
    PhanTramThueTTDB: numeric - Phần trăm thuế TTDB (%)

    ' Thông tin chi tiết thuế bảo vệ môi trường (nếu có)
    TaiKhoanThueBVMTId: uuid <<FK>> - ID tài khoản thuế BVMT (reference đến ENT_HeThongTaiKhoan)
    DonGiaBVMT: numeric - Đơn giá BVMT
    DonGiaBVMTQuyDoi: numeric - Đơn giá BVMT quy đổi
    TienThueBVMT: numeric - Tiền thuế BVMT
    TienThueBVMTQuyDoi: numeric - Tiền thuế BVMT quy đổi

    ' Thông tin nhập kho
    DonGiaNhapKho: numeric - Đơn giá nhập kho
    DonGiaNhapKhoQuyDoi: numeric - Đơn giá nhập kho quy đổi
    TongGiaTriNhapKho: numeric - Tổng giá trị nhập kho
    TongGiaTriNhapKhoQuyDoi: numeric - Tổng giá trị nhập kho quy đổi

    ' Thông tin tổng hợp
    ThanhTienTruocThue: numeric - Thành tiền
    ThanhTienSauThue: numeric - Thành tiền sau thuế
    ChiPhi: numeric - Chi phí
    TongTienThanhToan: numeric - Tổng tiền thanh toán

    ThanhTienTruocThueQuyDoi: numeric - Thành tiền
    ThanhTienSauThueQuyDoi: numeric - Thành tiền sau thuế
    ChiPhiQuyDoi: numeric - Chi phí
    TongTienThanhToanQuyDoi: numeric - Tổng tiền thanh toán

    ' Thông tin thống kê
    HopDongId: uuid <<FK>> - ID hợp đồng (reference đến ENT_HopDong)
    DonViId: uuid <<FK>> - ID đơn vị (reference đến ENT_DonVi)
    KhoanMucChiPhiId: uuid <<FK>> - ID khoản mục chi phí (reference đến ENT_KhoanMucChiPhi)
    VuViecId: uuid <<FK>> - ID vụ việc (reference đến ENT_CongTrinh)
}

entity ChiTietChungTuMuaDichVu
{
    *Id: uuid <<PK>> - ID bản ghi
    ' Tham chiếu tới các chứng từ liên quan
    ChungTuMuaDichVuId: uuid <<FK>> - ID chứng từ mua dịch vụ (reference đến ENT_ChungTuMuaDichVu)
    HoaDonMuaId: uuid <<FK>> - ID hóa đơn mua (reference đến ENT_HoaDonMua)

    ' Thông tin chi tiết dịch vụ
    MaDichVuId: uuid <<FK>> - ID mã hàng (reference đến ENT_DichVu)
    TenHang: string - Tên hàng hóa
    SoLuong: numeric - Số lượng


    DonGia: numeric! - Đơn giá
    DonGiaQuyDoi: numeric! - Đơn giá quy đổi
    ThanhTien: numeric! - Thành tiền
    ThanhTienQuyDoi: numeric! - Thành tiền
    ChietKhau: numeric - Chiết khấu
    ChietKhauQuyDoi: numeric - Chiết khấu
    ChietKhauPhanTram: numeric - Chiết khấu (%)
    DonViTinhId: uuid <<FK>> - ID đơn vị tính (reference đến ENT_DonViTinh)

    ' Thông tin chi tiết tài khoản kế toán
    TaiKhoanNo: uuid! <<FK>> - ID tài khoản nợ (reference đến ENT_HeThongTaiKhoan)
    TaiKhoanCo: uuid <<FK>> - ID tài khoản có (reference đến ENT_HeThongTaiKhoan)

    ' Thông tin chi tiết thuế GTGT
    ThueSuatGTGTId: uuid <<FK>> - ID thuế suất GTGT (reference đến ENT_ThueSuatGTGT)
    TaiKhoanThueGTGTId: uuid <<FK>> - ID tài khoản thuế GTGT (reference đến ENT_HeThongTaiKhoan)
    TienThueGTGT: numeric - Tiền thuế GTGT
    TienThueGTGTQuyDoi: numeric - Tiền thuế GTGT quy đổi
    TinhChatThueGTGTId: uuid <<FK>> - ID tính chất thuế GTGT (reference đến ENT_TinhChatThueGTGT)

    ' Thông tin tổng hợp
    ThanhTienTruocThue: numeric - Thành tiền
    TongTienThanhToan: numeric - Tổng tiền thanh toán

    ThanhTienTruocThueQuyDoi: numeric - Thành tiền
    TongTienThanhToanQuyDoi: numeric - Tổng tiền thanh toán

    ' Thông tin thống kê
    HopDongId: uuid <<FK>> - ID hợp đồng (reference đến ENT_HopDong)
    DonViId: uuid <<FK>> - ID đơn vị (reference đến ENT_DonVi)
    KhoanMucChiPhiId: uuid <<FK>> - ID khoản mục chi phí (reference đến ENT_KhoanMucChiPhi)
    VuViecId: uuid <<FK>> - ID vụ việc (reference đến ENT_CongTrinh)
}

entity ChiPhiMuaHang {
    *Id: uuid <<PK>> - ID bản ghi
    ChungTuMuaHangId: uuid! <<FK>> - ID chứng từ mua hàng (reference đến ENT_ChungTuMuaHang)
    HoaDonId: uuid <<FK>> - ID hóa đơn mua hàng (reference đến ENT_HoaDonMua)

    MaDichVuId: uuid <<FK>> - ID mã dịch vụ (reference đến ENT_DichVu)
    TenDichVuId: string - Tên dịch vụ
    NhaCungCapId: uuid <<FK>> - ID nhà cung cấp (reference đến ENT_NhaCungCap)
    ThanhTien: numeric! - Thành tiền
    ThanhTienQuyDoi: numeric! - Thành tiền quy đổi

    ' Thông tin chi tiết thuế GTGT
    ThueSuatGTGTId: uuid <<FK>> - ID thuế suất GTGT (reference đến ENT_ThueSuatGTGT)
    TaiKhoanThueGTGTId: uuid <<FK>> - ID tài khoản thuế GTGT (reference đến ENT_HeThongTaiKhoan)
    TienThueGTGT: numeric - Tiền thuế GTGT
    TienThueGTGTQuyDoi: numeric - Tiền thuế GTGT quy đổi
    TinhChatThueGTGTId: uuid <<FK>> - ID tính chất thuế GTGT (reference đến ENT_TinhChatThueGTGT)
}

entity ChungTuPhanBo
{
    *Id: uuid! <<PK>> - ID bản ghi
    SoChungTu: string! - Số chứng từ phân bổ
    NgayChungTu: datetime! - Thời gian phân bổ
    NhaCungCapId: uuid! <<FK>> - ID nhà cung cấp (reference đến ENT_NhaCungCap)
    MoTa: string - Diễn giải
}

entity PhanBoHoaDon
{
    *Id: uuid! <<PK>> - ID bản ghi
    ChungTuPhanBoId: uuid! <<FK>> - ID chứng từ phân bổ (reference đến ENT_ChungTuPhanBo)
    'Mapping keys
    ChungTuChiTienId: uuid! <<FK>> - ID phiếu chi (reference đến ENT_ChungTuChiTien)
    HoaDonMuaId: uuid! <<FK>> - ID hóa đơn mua hàng (reference đến ENT_HoaDonMua hoặc ENT_ChungTuMuaHang)
    SoTienPhanBo: numeric! - Số tiền phân bổ
}

'------------------------------------------------------------------------------
' Chứng từ trả lại hàng mua
'------------------------------------------------------------------------------

entity ChungTuTraLaiHangMua
{
    *Id: uuid <<PK>> - ID bản ghi

    ' Thuộc tính nghiệp vụ chung
    PhuongThucLapHoaDon: enum! - Hình thức (Người bán xuất hóa đơn điều chỉnh/Người mua xuất hóa đơn/Không có hóa đơn)
    ThuTienNgay: boolean! - Giảm trừ công nợ/Thu tiền ngay
    HinhThucThanhToan: enum - Tiền mặt/Chuyển khoản (chỉ có giá trị nếu ThuTienNgay = True)
    TraLaiHangTrongKho: boolean! - Trả lại hàng trong kho (true/false)

    ' Thông tin chứng từ null nếu có phiếu xuất kho
    SoChungTu: string - Số chứng từ
    NgayChungTu: date - Ngày chứng từ
    NgayHachToan: date - Ngày hạch toán
    MoTa: string - Diễn giải

    ' Thông tin loại tiền và tỷ giá
    LoaiTienId: uuid! <<FK>> - ID loại tiền tệ (reference đến ENT_LoaiTien)
    TyGia: numeric! - Tỷ giá

    ' Thông tin nhà cung cấp null nếu có phiếu xuất kho
    NhaCungCapId: uuid! <<FK>> - ID nhà cung cấp
    TenNhaCungCap: string! - Tên nhà cung cấp
    DiaChi: string - Địa chỉ nhà cung cấp
    MaSoThue: string - Mã số thuế

    ' Thông tin nhân viên
    NhanVienId: uuid <<FK>> - ID nhân viên mua hàng

    ' Nhóm thông tin tổng hợp theo chứng từ
    TongTienHangHoa: numeric - Tổng tiền hàng hóa trả lại
    TongTienThueGTGT: numeric - Tổng tiền thuế GTGT giảm đi
    TongTienThanhToan: numeric - Tổng tiền thanh toán/điều chỉnh

    ' Nhóm thông tin quy đổi
    TongTienHangHoaQuyDoi: numeric - Tổng tiền hàng hóa trả lại quy đổi ra đồng tiền hạch toán
    TongTienThueGTGTQuyDoi: numeric - Tổng tiền thuế GTGT giảm đi quy đổi ra đồng tiền hạch toán
    TongTienThanhToanQuyDoi: numeric - Tổng tiền thanh toán/điều chỉnh quy đổi ra đồng tiền hạch toán

    ' Nhóm thông tin thanh toán
    SoTienDaThanhToan: numeric - Số tiền đã thanh toán
    SoTienDaThanhToanQuyDoi: numeric - Số tiền đã thanh toán quy đổi

    ' Nhóm thông tin trạng thái
    TrangThaiChungTu: enum! - Trạng thái chứng từ (Chưa ghi sổ, Đã ghi sổ)
    TrangThaiThanhToan: enum! - Trạng thái thanh toán (Đã thanh toán / Chưa thanh toán / Đã thanh toán một phần)
}

entity ChiTietChungTuTraLaiHangMua
{
    *Id: uuid! <<PK>> - ID bản ghi
    ' Tham chiếu tới các chứng từ liên quan
    ChungTuTraLaiHangMuaId: uuid! <<FK>> - ID chứng từ trả lại hàng mua (reference đến ENT_ChungTuTraLaiHangMua)
    PhieuXuatKhoId: uuid <<FK>> - ID phiếu xuất kho (reference đến ENT_PhieuXuatKhoTraLaiHangMua)
    ChungTuMuaHangId: uuid <<FK>> - ID chứng từ mua hàng nếu mặt hàng được chọn từ chứng từ (reference đến ENT_ChungTuMuaHang)

    ' Thông tin chi tiết hàng hóa
    MaHangId: uuid! <<FK>> - ID mã hàng (reference đến ENT_VatTu)
    TenHang: string - Tên hàng hóa
    SoLuong: numeric! - Số lượng
    DonGia: numeric! - Đơn giá
    DonGiaQuyDoi: numeric! - Đơn giá quy đổi
    ThanhTien: numeric! - Thành tiền
    ThanhTienQuyDoi: numeric! - Thành tiền
    DonViTinhId: uuid <<FK>> - ID đơn vị tính (reference đến ENT_DonViTinh)
    HeSoQuyDoi: numeric! - Hệ số quy đổi từ đơn vị tính
    MaKhoId: uuid <<FK>> - ID kho (reference đến ENT_Kho)
    SoLo: string - Số lô
    HanSuDung: date - Hạn sử dụng

    ' Thông tin chi tiết tài khoản kế toán
    TaiKhoanNo: uuid! <<FK>> - ID tài khoản nợ (reference đến ENT_HeThongTaiKhoan)
    TaiKhoanCo: uuid! <<FK>> - ID tài khoản có (reference đến ENT_HeThongTaiKhoan)

    ' Thông tin chi tiết thuế GTGT
    ThueSuatGTGTId: uuid <<FK>> - ID thuế suất GTGT (reference đến ENT_ThueSuatGTGT)
    TaiKhoanThueGTGTId: uuid <<FK>> - ID tài khoản thuế GTGT (reference đến ENT_HeThongTaiKhoan)
    TienThueGTGT: numeric - Tiền thuế GTGT
    TienThueGTGTQuyDoi: numeric - Tiền thuế GTGT quy đổi
    TinhChatThueGTGTId: uuid <<FK>> - ID tính chất thuế GTGT (reference đến ENT_TinhChatThueGTGT)

    ' Thông tin tổng hợp
    TongTienHangHoa: numeric - Tổng tiền hàng hóa trả lại
    TongTienThue: numeric - Tổng tiền thuế
    TongTienThanhToan: numeric - Tổng tiền thanh toán

    TongTienHangHoaQuyDoi: numeric - Tổng tiền hàng hóa trả lại
    TongTienThueQuyDoi: numeric - Tổng tiền thuế
    TongTienThanhToanQuyDoi: numeric - Tổng tiền thanh toán

    ' Thông tin thống kê
    DonViId: uuid <<FK>> - ID đơn vị (reference đến ENT_DonVi)
    KhoanMucChiPhiId: uuid <<FK>> - ID khoản mục chi phí (reference đến ENT_KhoanMucChiPhi)
    VuViecId: uuid <<FK>> - ID vụ việc (reference đến ENT_CongTrinh)
    DoiTuongTHCPId: uuid <<FK>> - ID đối tượng THCP (reference đến ENT_DoiTuongTHCP)
}

entity HoaDonDieuChinh
{
    *Id: uuid <<PK>> - ID bản ghi

    ' Tham chiếu chứng từ liên quan
    ChungTuTraLaiHangMua: array[uuid] - Danh sách ID chứng từ trả lại hàng mua (reference đến ENT_ChungTuTraLaiHangMua)
    ChungTuDieuChinhGiaHangMua: array[uuid] - Danh sách ID chứng từ điều chỉnh giá hàng mua (reference đến ENT_ChungTuDieuChinhGiaHangMua)

    ' Thông tin hóa đơn điều chỉnh
    MauSoHoaDonId: uuid <<FK>> - ID mẫu số hóa đơn (reference đến ENT_MauSoHoaDon)
    KyHieuHoaDon: string - Ký hiệu hóa đơn
    SoHoaDon: string - Số hóa đơn
    NgayHoaDon: date - Ngày hóa đơn

    ' Thông tin nhà cung cấp
    NhaCungCapId: uuid <<FK>> - ID nhà cung cấp (reference đến ENT_NhaCungCap)
    TenNhaCungCap: string - Tên nhà cung cấp
    MaSoThue: string - Mã số thuế nhà cung cấp
    DiaChi: string - Địa chỉ nhà cung cấp
    MoTa: string - Diễn giải
}

entity HoaDonTraLaiHangMua
{
    *Id: uuid <<PK>> - ID bản ghi

    ' Tham chiếu chứng từ liên quan
    ChungTuTraLaiHangMua: array[uuid] - Danh sách ID chứng từ trả lại hàng mua (reference đến ENT_ChungTuTraLaiHangMua)

    ' Thông tin hóa đơn trả lại hàng
    MauSoHoaDonId: uuid <<FK>> - ID mẫu số hóa đơn (reference đến ENT_MauSoHoaDon)
    KyHieuHoaDon: string - Ký hiệu hóa đơn
    SoHoaDon: string - Số hóa đơn
    NgayHoaDon: date - Ngày hóa đơn

    ' Thông tin nhà cung cấp
    NhaCungCapId: uuid <<FK>> - ID nhà cung cấp (reference đến ENT_NhaCungCap)
    TenNhaCungCap: string - Tên nhà cung cấp
    MaSoThue: string - Mã số thuế nhà cung cấp
    DiaChi: string - Địa chỉ nhà cung cấp
    GhiChu: string - Ghi chú

    ' Thông tin người nhận và thanh toán
    NguoiNhan: string - Người nhận
    HinhThucTT: enum - Hình thức thanh toán (Tiền mặt, Chuyển khoản, Tiền mặt hoặc Chuyển khoản)
    TaiKhoanNganHangId: uuid <<FK>> - ID tài khoản ngân hàng (reference đến ENT_TaiKhoanNganHang)
    NhanVienId: uuid <<FK>> - ID nhân viên (reference đến ENT_NhanVien)
    MoTa: string - Diễn giải
}

entity PhieuXuatKhoTraLaiHangMua
{
    *Id: uuid <<PK>> - ID bản ghi

    ' Thông tin nhà cung cấp
    NhaCungCapId: uuid! <<FK>> - ID nhà cung cấp (reference đến ENT_NhaCungCap)
    TenNhaCungCap: string! - Tên nhà cung cấp
    DiaChi: string - Địa chỉ nhà cung cấp
    NguoiNhan: string - Người nhận hàng

    ' Thông tin nhân viên
    NhanVienId: uuid <<FK>> - ID nhân viên xuất kho (reference đến ENT_NhanVien)

    ' Thông tin chứng từ
    SoChungTu: string - Số chứng từ
    NgayChungTu: date - Ngày chứng từ
    NgayHachToan: date - Ngày hạch toán
    MoTa: string - Diễn giải

    ' Thông tin loại tiền và tỷ giá
    LoaiTienId: uuid <<FK>> - ID loại tiền tệ (reference đến ENT_LoaiTien)
    TyGia: numeric! - Tỷ giá
}

'------------------------------------------------------------------------------
' Chứng từ điều chỉnh giá hàng mua
'------------------------------------------------------------------------------

entity ChungTuDieuChinhGiaHangMua
{
    *Id: uuid <<PK>> - ID bản ghi

    ' Thuộc tính nghiệp vụ chung
    LyDoDieuChinh: enum! - Giảm giá hàng mua/Tăng giá hàng mua/Điều chỉnh tăng & giảm giá hàng mua
    TrangThaiHoaDon: enum! - Có hóa đơn/Không có hóa đơn
    ThanhToanNgay: boolean! - Điều chỉnh công nợ/Thanh toán ngay
    HinhThucThanhToan: enum - Phiếu thu/Giấy báo có/Phiếu chi/Ủy nhiệm chi/Séc tiền mặt/Séc chuyển khoản
    DieuChinhGiaTriHangNhapKho: boolean! - Điều chỉnh giá trị hàng nhập kho (true/false)

    ' Thông tin chứng từ
    SoChungTu: string - Số chứng từ
    NgayChungTu: date - Ngày chứng từ
    NgayHachToan: date - Ngày hạch toán
    MoTa: string - Diễn giải

    ' Thông tin loại tiền và tỷ giá
    LoaiTienId: uuid! <<FK>> - ID loại tiền tệ (reference đến ENT_LoaiTien)
    TyGia: numeric! - Tỷ giá

    ' Thông tin nhà cung cấp
    NhaCungCapId: uuid! <<FK>> - ID nhà cung cấp
    TenNhaCungCap: string! - Tên nhà cung cấp
    DiaChi: string - Địa chỉ nhà cung cấp
    MaSoThue: string - Mã số thuế

    ' Thông tin nhân viên
    NhanVienId: uuid <<FK>> - ID nhân viên mua hàng

    ' Nhóm thông tin tổng hợp theo chứng từ
    TongTienHangHoa: numeric - Tổng tiền hàng hóa điều chỉnh
    TongTienThueGTGT: numeric - Tổng tiền thuế GTGT điều chỉnh
    TongTienThanhToan: numeric - Tổng tiền thanh toán

    ' Nhóm thông tin quy đổi
    TongTienHangHoaQuyDoi: numeric - Tổng tiền hàng hóa điều chỉnh quy đổi ra đồng tiền hạch toán
    TongTienThueGTGTQuyDoi: numeric - Tổng tiền thuế GTGT điều chỉnh quy đổi ra đồng tiền hạch toán
    TongTienThanhToanQuyDoi: numeric - Tổng tiền thanh toán quy đổi ra đồng tiền hạch toán

    ' Nhóm thông tin thanh toán
    SoTienDaThanhToan: numeric - Số tiền đã thanh toán
    SoTienDaThanhToanQuyDoi: numeric - Số tiền đã thanh toán quy đổi

    ' Nhóm thông tin trạng thái
    TrangThaiChungTu: enum! - Trạng thái chứng từ (Chưa ghi sổ, Đã ghi sổ)
    TrangThaiThanhToan: enum! - Trạng thái thanh toán (Đã thanh toán / Chưa thanh toán / Đã thanh toán một phần)
}

entity ChiTietChungTuDieuChinhGiaHangMua
{
    *Id: uuid! <<PK>> - ID bản ghi
    ' Tham chiếu tới các chứng từ liên quan
    ChungTuDieuChinhGiaHangMuaId: uuid! <<FK>> - ID chứng từ trả lại hàng mua (reference đến ENT_ChungTuTraLaiHangMua)
    ChungTuMuaHangId: uuid <<FK>> - ID chứng từ mua hàng nếu mặt hàng được chọn từ chứng từ (reference đến ENT_ChungTuMuaHang)
    ChungTuMuaDichVuId: uuid <<FK>> - ID chứng từ mua dịch vụ nếu dịch vụ được chọn từ chứng từ (reference đến ENT_ChungTuMuaDichVu)

    LoaiDieuChinh: enum! - Tăng/Giảm

    ' Thông tin chi tiết hàng hóa
    MaHangId: uuid! <<FK>> - ID mã vật tư (reference đến ENT_VatTu)
    TenHang: string - Tên vật tư (hàng hóa, dịch vụ,...)
    SoLuong: numeric - Số lượng
    DonGia: numeric - Đơn giá
    DonGiaQuyDoi: numeric! - Đơn giá quy đổi
    ThanhTien: numeric! - Thành tiền
    ThanhTienQuyDoi: numeric! - Thành tiền
    DonViTinhId: uuid <<FK>> - ID đơn vị tính (reference đến ENT_DonViTinh)
    MaKhoId: uuid <<FK>> - ID kho (reference đến ENT_Kho)
    SoLo: string - Số lô
    HanSuDung: date - Hạn sử dụng

    ' Thông tin chi tiết tài khoản kế toán
    TaiKhoanNo: uuid! <<FK>> - ID tài khoản nợ (reference đến ENT_HeThongTaiKhoan)
    TaiKhoanCo: uuid! <<FK>> - ID tài khoản có (reference đến ENT_HeThongTaiKhoan)

    ' Thông tin chi tiết thuế GTGT
    ThueSuatGTGTId: uuid <<FK>> - ID thuế suất GTGT (reference đến ENT_ThueSuatGTGT)
    TaiKhoanThueGTGTId: uuid <<FK>> - ID tài khoản thuế GTGT (reference đến ENT_HeThongTaiKhoan)
    TienThueGTGT: numeric - Tiền thuế GTGT
    TienThueGTGTQuyDoi: numeric - Tiền thuế GTGT quy đổi
    TinhChatThueGTGTId: uuid <<FK>> - ID tính chất thuế GTGT (reference đến ENT_TinhChatThueGTGT)

    ' Thông tin tổng hợp
    TongTienHangHoa: numeric - Tổng tiền hàng điều chỉnh
    TongTienThue: numeric - Tổng tiền thuế điều chỉnh
    TongTienThanhToan: numeric - Tổng tiền thanh toán

    TongTienHangHoaQuyDoi: numeric - Tổng tiền hàng hàng điều chỉnh
    TongTienThueQuyDoi: numeric - Tổng tiền thuế điều chỉnh
    TongTienThanhToanQuyDoi: numeric - Tổng tiền thanh toán

    ' Thông tin thống kê
    DonViId: uuid <<FK>> - ID đơn vị (reference đến ENT_DonVi)
    KhoanMucChiPhiId: uuid <<FK>> - ID khoản mục chi phí (reference đến ENT_KhoanMucChiPhi)
    VuViecId: uuid <<FK>> - ID vụ việc (reference đến ENT_CongTrinh)
    DoiTuongTHCPId: uuid <<FK>> - ID đối tượng THCP (reference đến ENT_DoiTuongTHCP)
} 

@enduml
